[profile.default]
src = "src"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.30"
base = true
remappings = [
  "base-std/=lib/base-std/src/",
  "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 120
